[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "python --version",
  "pip install -r backend/requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd backend && gunicorn app:app -w 2 -t 120 --keep-alive 5 --log-level info"